### ISSUE TITLE
xPIMapping Set-TargetResource calls Rename-PIMappingDSC with incorrect parameter name "NewName"

### ISSUE THREAD

**Issue by LYarnall** [osisoft/PI-Security-DSC#35]
xPIMapping Set-TargetResource calls Rename-PIMappingDSC with the argument "NewName". However, Rename-PIMappingDSC accepts the parameter "Name" instead.

This causes Name to be $null and when Rename-PIMapping is called, it fails with
`Cannot validate argument on parameter 'NewName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.`

To fix this, Set-TargetResource should call Rename-PIMappingDSC with the correct parameter "Name".

**Comment by hpaul-osi** [comment]
This needs a little more investigation.  The current code passed all integration and unit test before checkin and matches the official documentation for [Rename-PIMapping](https://techsupport.osisoft.com/Documentation/PI-Powershell/PI-DataArchive/Rename-PIMapping.html) which contains the following example.

```PowerShell
Rename-PIMapping -ExistingName "Windows_S-1-5-21-2084324470-1890137325-1469997231-53017" -NewName "Jane Doe" -Connection $con
```

Furthermore, using -ExistingName and -Name returns an error about redundant parameters.
```PowerShell
PS C:\Users\hpaul> Rename-PIMapping -Connection $connect -ExistingName "myTestMapping" -Name "myTestMappingRenamed"

Rename-PIMapping : Cannot bind parameter because parameter 'ExistingName' is specified 
more than once. To provide multiple values to parameters that can accept multiple 
values, use the array syntax. For example, "-parameter value1,value2,value3".
At line:1 char:68
+ ... Mapping -Connection $connect -ExistingName "wmurdocktest" -Name "wmt"
+                                                               ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Rename-PIMapping], ParameterBindingE 
   xception
    + FullyQualifiedErrorId : ParameterAlreadyBound,OSIsoft.PowerShell.RenamePIMapping
```

I suspect there may have been a change in behavior with OSIsoft.PowerShell between versions, so a fix may be necessary, but we'll want to make the most reliable fix and follow up with the doc team if necessary.

**Comment by LYarnall** [comment]
@hpaul-osi 
Per our conversation the issue occurs when calling the local function Rename-PIMappingDSC rather than the cmdlet Rename-PIMapping.

I updated the pull request to keep more consistent parameter names between Rename-PIMapping and Rename-PIMappingDSC.

**Comment by hpaul-osi** [comment]
Thanks, @LYarnall.  Apologies for my misreading and thanks for making the tweak to the parameter names.
